### ISSUE TITLE
Tracking Ideas for June Letter

### ISSUE THREAD

**Issue by treyhuffine** [codingdigest/codingdigest#2]
- [x] - React Router 4 release (Declarative routing for React. The router for React finally becomes React Router).
- [x] - React 15.5 release (last major before React 16)
- [x] - Kotlin is a first class citizen for Android
- [x] - Styled components v2 released (what's the future of style for React?)
- [x] - React 16 almost ready: 99.6% of tests passing as of today (https://twitter.com/dan_abramov/status/867826646228889600)
- [x] - Web Assembly browser consensus

**Comment by treyhuffine** [comment]
- [x] npm 5.0.0 released

**Comment by treyhuffine** [comment]
Polymer 2
